# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more optional fields (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that lines starting with # are comments, and will not be read by the game.
# The following properties have been injected by the build script.
# Please do not change them. They will not be updated automatically.
#
# neoforge_version="21.1.152"
# minecraft_version="1.21.1"
# mod_version="1.0.0-1.21.1"
# mod_id="mob_friends"

# The loader random float for versions of the modloader. This is selecting between the compatible versions.
# A value of 0 indicates the lowest supported version.
# A value of 1 indicates the highest supported version.
# The default value is 0.
loaderVersion = "[1,)" # Suggestions: "[1,)"

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your mod's license.
# The SPDX license list can be found here: https://spdx.org/licenses/
license = "All Rights Reserved"

# A URL to the issue tracker for your mod. This will be displayed in the mod list when hovered.
issueTrackerURL="https://github.com/Sakey-ez/MobFriends/issues" #optional

# A list of mods - how many mods loaded in configured in this file.
[[mods]]

# The modid of the mod
modId = "mob_friends" #mandatory

# The version number of the mod
version = "1.0.0-1.21.1" #mandatory

# A display name for the mod
displayName = "Mob Friends" #mandatory

# A URL to query for updates for this mod. See the JSON format for this file on the NeoForge wiki.
# updateJSONURL="https://change.me.to.your.update.json.if.you.have.one/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/Sakey-ez/MobFriends" #optional



# A text field displayed in the mod UI
authors="Sake" #optional

# The description text for the mod (multi line!) (#mandatory)
description = '''
Make friends with mobs and build your own mob factions!
'''

# A dependency - use the .toml file format for specifying dependencies.
[[dependencies.mob_friends]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mob_friends]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"