modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory
license="All Rights Reserved"

[[mods]] #mandatory
modId="mob_friends" #mandatory
version="1.0.0-1.21.1" #mandatory
displayName="Mob Friends" #mandatory
authors="sake_yez" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''You can make friends with some mobs.'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="mob_friends.mixins.json"

[[data_pack]]
registry_name = "mob_friends"
path = "mob_friends_data"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.mob_friends]]
modId="neoforge"
type="required"
versionRange="[21,)" #
ordering="NONE"
side="BOTH"

# Here's another dependency
[[dependencies.mob_friends]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)" #
ordering="NONE"
side="BOTH"